openapi: 3.0.3
info:
  title: Lesson API Contract
  version: 1.0.0
  description: API for managing lesson information and progress.

paths:
  /api/child/curriculum/{curriculum_id}/lessons:
    get:
      summary: Get Curriculum Lessons
      description: Returns curriculum details and lessons with progress status for the authenticated child.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: curriculum_id
          schema:
            type: integer
          required: true
          description: Curriculum ID to filter lessons
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  curriculum:
                    type: object
                    properties:
                      curriculum_id:
                        type: integer
                      name:
                        type: string
                  lessons:
                    type: array
                    items:
                      type: object
                      properties:
                        lesson_id:
                          type: integer
                        title:
                          type: string
                        image:
                          type: string
                          format: url
                          nullable: true
                          description: URL to the lesson's image. Can be null.
                        description:
                          type: string
                        progress_status:
                          type: number
                          format: float
                          minimum: 0
                          maximum: 100
              examples:
                example1:
                  value:
                    curriculum:
                      curriculum_id: 1
                      name: "Math Grade 1"
                    lessons:
                      - lesson_id: 101
                        title: "Counting to 10"
                        image: "http://example.com/counting.png"
                        description: "Introduction to numbers."
                        progress_status: 80.0
                      - lesson_id: 102
                        title: "Basic Addition"
                        image: null
                        description: "Adding single-digit numbers."
                        progress_status: 45.0
        "401":
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token is missing"
        "403":
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Insufficient permissions"
        "404":
          description: Skill not found or no lessons found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      skill_not_found:
                        value: "Skill not found"
                      no_lessons:
                        value: "No lessons found for this skill"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Database error occurred"
                  details:
                    type: string
                    example: "Connection timeout"
      x-progress-calculation:
        - formula: "progress_status = (attempted_activities + attempted_quizzes) / (total_activities + total_quizzes) * 100"
        - notes:
            - Only includes activities/quizzes for this lesson and the authenticated child
            - "`attempted_activities`: Activities that have been attempted (with submissions in history)"
            - "`attempted_quizzes`: Quizzes that have been attempted (regardless of score)"
            - If no activities or quizzes exist for a lesson, progress_status defaults to 100%

  /api/child/lesson/{lesson_id}:
    get:
      summary: Get Lesson Details
      description: Returns lesson content and completion status for the authenticated child.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: lesson_id
          schema:
            type: integer
          required: true
          description: Lesson ID
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  lesson_id:
                    type: integer
                    description: Unique identifier for the lesson
                  title:
                    type: string
                    description: Title of the lesson
                  content:
                    type: string
                    description: Content of the lesson
                  image:
                    type: string
                    format: url
                    nullable: true
                    description: URL to the lesson's image. Can be null.
                  completed_at:
                    type: string
                    format: date-time
                    nullable: true
                    description: ISO format datetime when lesson was completed, null if not completed.
              examples:
                completed_lesson:
                  value:
                    lesson_id: 101
                    title: "Introduction to Addition"
                    content: "Learn the basics of adding numbers together..."
                    image: "https://example.com/lesson101.jpg"
                    completed_at: "2024-12-01T10:30:45.000Z"
                incomplete_lesson:
                  value:
                    lesson_id: 102
                    title: "Subtraction Basics"
                    content: "Understanding how to subtract numbers..."
                    image: null
                    completed_at: null
        "401":
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token is missing"
        "403":
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Insufficient permissions"
        "404":
          description: Lesson not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Lesson not found"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Database error occurred"
                  details:
                    type: string
                    example: "Connection timeout"

  /api/child/lesson/{lesson_id}/mark-read:
    post:
      summary: Mark Lesson as Read
      description: |
        Records lesson completion timestamp for the authenticated child.
        
        Behavior Notes:
        - Idempotent operation: If lesson is already completed, returns 200
        - Each child-lesson combination can only have one completion record
        - Completion timestamp cannot be modified once set
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: lesson_id
          schema:
            type: integer
          required: true
          description: Lesson ID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                completed_at:
                  type: string
                  format: date-time
                  nullable: true
                  description: "ISO 8601 datetime format. Supports 'Z' (UTC) or timezone offsets (+HH:MM). If not provided, uses current server time."
            examples:
              with_utc_timestamp:
                value:
                  completed_at: "2024-12-01T10:30:45.000Z"
              with_timezone_timestamp:
                value:
                  completed_at: "2024-12-01T10:30:45+05:30"
              without_timestamp:
                value: {}
      responses:
        "201":
          description: Lesson marked as completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lesson marked as completed"
        "200":
          description: Lesson was already completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lesson already completed"
        "400":
          description: Bad request - Invalid date format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid date format"
        "401":
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token is missing"
        "403":
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Insufficient permissions"
        "404":
          description: Lesson not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Lesson not found"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Database error occurred"
                  details:
                    type: string
                    example: "Connection timeout"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication token required for child access
