openapi: 3.0.3
info:
  title: Curriculum API Contract
  version: 1.0.0
  description: API for managing curriculum information.

paths:
  /api/child/{child_id}/curriculums:
    get:
      summary: Get Child's Curriculums
      description: Returns a list of curriculums for a specific child, filtered by age group and including progress status.
      parameters:
        - in: path
          name: child_id
          schema:
            type: integer
          required: true
          description: Unique identifier for the child
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  curriculums:
                    type: array
                    items:
                      type: object
                      properties:
                        curriculum_id:
                          type: integer
                          description: Unique identifier for the curriculum.
                        name:
                          type: string
                          description: Name of the curriculum.
                        image:
                          type: string
                          format: url
                          description: URL to the curriculum's image.
                        description:
                          type: string
                          description: A brief description of the curriculum.
                        progress_status:
                          type: number
                          format: float
                          minimum: 0
                          maximum: 100
                          description: The progress status of the child in this curriculum (0-100%).
              examples:
                example1:
                  value:
                    curriculums:
                      - curriculum_id: 101
                        name: "Early Math"
                        image: "https://example.com/math.png"
                        description: "Basic mathematical concepts for young learners."
                        progress_status: 75.5
                      - curriculum_id: 102
                        name: "Creative Writing"
                        image: "https://example.com/writing.png"
                        description: "Develops storytelling and imaginative writing skills."
                        progress_status: 30.0
                      - curriculum_id: 103
                        name: "Introduction to Coding"
                        image: "https://example.com/coding.png"
                        description: "Fundamentals of programming for beginners."
                        progress_status: 90.2
      x-data-requirements:
        - Child Age Group Filtering:
            - Fetch child's age from `child_id`
            - Only return curriculums matching the child's age group
        - Progress Calculation:
            Formula: "`progress_status = (completed_items / total_items) * 100`"
            Where:
              - completed_items: "Lessons marked complete, Activities with submissions, Quizzes with passing scores"
              - total_items: "Total lessons, Total activities, Total quizzes (All counts specific to the curriculum)"
