openapi: 3.0.3
info:
  title: Curriculum API Contract
  version: 1.0.0
  description: API for managing curriculum information.

paths:
  /api/child/curriculums:
    get:
      summary: Get Child's Curriculums
      description: Returns a list of curriculums for the authenticated child, filtered by age group and including progress status.
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  curriculums:
                    type: array
                    items:
                      type: object
                      properties:
                        curriculum_id:
                          type: integer
                          description: Unique identifier for the curriculum.
                        name:
                          type: string
                          description: Name of the curriculum.
                        image:
                          type: string
                          format: url
                          nullable: true
                          description: URL to the curriculum's image. Currently always null.
                        description:
                          type: string
                          description: A brief description of the curriculum.
                        progress_status:
                          type: number
                          format: float
                          minimum: 0
                          maximum: 100
                          description: The progress status of the child in this curriculum (0-100%).
              examples:
                example1:
                  value:
                    curriculums:
                      - curriculum_id: 101
                        name: "Early Math"
                        image: null
                        description: "Basic mathematical concepts for young learners."
                        progress_status: 75.5
                      - curriculum_id: 102
                        name: "Creative Writing"
                        image: null
                        description: "Develops storytelling and imaginative writing skills."
                        progress_status: 30.0
                      - curriculum_id: 103
                        name: "Introduction to Coding"
                        image: null
                        description: "Fundamentals of programming for beginners."
                        progress_status: 90.2
        "401":
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token is missing"
        "403":
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Insufficient permissions"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Database error occurred"
      x-data-requirements:
        - Child Age Group Filtering:
            - Fetch child's age from authenticated child's profile
            - Only return curriculums matching the child's age group
        - Progress Calculation:
            Formula: "`progress_status = (completed_items / total_items) * 100`"
            Where:
              - completed_items: "Lessons marked complete, Activities with submissions, Quizzes with passing scores"
              - total_items: "Total lessons, Total activities, Total quizzes (All counts specific to the curriculum)"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication token required for child access
