openapi: 3.0.3
info:
  title: Quiz API Contract
  version: 1.0.0
  description: API for managing quiz information and history.

paths:
  /api/child/{child_id}/curriculum/{curriculum_id}/lesson/{lesson_id}/quizzes:
    get:
      summary: Get Lesson Quizzes
      description: Returns curriculum, lesson, and quizzes associated with them.
      parameters:
        - in: path
          name: child_id
          schema:
            type: integer
          required: true
          description: Child ID
        - in: path
          name: curriculum_id
          schema:
            type: integer
          required: true
          description: Curriculum ID
        - in: path
          name: lesson_id
          schema:
            type: integer
          required: true
          description: Lesson ID
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  curriculum:
                    type: object
                    properties:
                      curriculum_id:
                        type: integer
                      name:
                        type: string
                  lesson:
                    type: object
                    properties:
                      lesson_id:
                        type: integer
                      title:
                        type: string
                  quizzes:
                    type: array
                    items:
                      type: object
                      properties:
                        quiz_id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                        time_duration:
                          type: string
                          example: "5 mins"
                        difficulty:
                          type: string
                          enum: [Easy, Medium, Hard]
                        progress_status:
                          type: number
                          enum: [0, 100]
                          description: 0 if no attempts, 100 if at least one attempt.
                        image:
                          type: string
                          format: url
              examples:
                example1:
                  value:
                    curriculum:
                      curriculum_id: 1
                      name: "Math Basics"
                    lesson:
                      lesson_id: 101
                      title: "Introduction to Numbers"
                    quizzes:
                      - quiz_id: 201
                        name: "Counting Quiz"
                        description: "Test your counting skills."
                        time_duration: "5 mins"
                        difficulty: "Easy"
                        progress_status: 100
                        image: "http://example.com/quiz1.png"
                      - quiz_id: 202
                        name: "Addition Challenge"
                        description: "Quick quiz on basic addition."
                        time_duration: "10 mins"
                        difficulty: "Medium"
                        progress_status: 0
                        image: "http://example.com/quiz2.png"
      x-progress-calculation:
        - "`progress_status = 100` if child has attempted quiz at least once"
        - "`progress_status = 0` if no attempts exist"

  /api/child/{child_id}/quiz/{quiz_id}/history:
    get:
      summary: Get Quiz History
      description: Returns quiz attempt history for a specific child and quiz.
      parameters:
        - in: path
          name: child_id
          schema:
            type: integer
          required: true
          description: Child ID
        - in: path
          name: quiz_id
          schema:
            type: integer
          required: true
          description: Quiz ID
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  quizzes_history:
                    type: array
                    items:
                      type: object
                      properties:
                        quiz_history_id:
                          type: integer
                        quiz_id:
                          type: integer
                        attempted_at:
                          type: string
                          format: date-time
                          description: ISO format datetime of the attempt.
                        score:
                          type: number
                        feedback:
                          type: object
                          properties:
                            admin:
                              type: string
                            parent:
                              type: string
              examples:
                example1:
                  value:
                    quizzes_history:
                      - quiz_history_id: 1
                        quiz_id: 201
                        attempted_at: "2024-07-19T10:00:00Z"
                        score: 85
                        feedback:
                          admin: "Great effort!"
                          parent: "Keep up the good work!"
                      - quiz_history_id: 2
                        quiz_id: 201
                        attempted_at: "2024-07-18T09:30:00Z"
                        score: 70
                        feedback:
                          admin: "Good try."
                          parent: ""
