openapi: 3.0.3
info:
  title: Lesson API Contract
  version: 1.0.0
  description: API for managing lesson information and progress.

paths:
  /api/child/{child_id}/curriculum/{curriculum_id}/lessons:
    get:
      summary: Get Curriculum Lessons
      description: Returns curriculum details and lessons with progress status.
      parameters:
        - in: path
          name: child_id
          schema:
            type: integer
          required: true
          description: Unique identifier for the child
        - in: path
          name: curriculum_id
          schema:
            type: integer
          required: true
          description: Curriculum ID to filter lessons
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  curriculum:
                    type: object
                    properties:
                      curriculum_id:
                        type: integer
                      name:
                        type: string
                  lessons:
                    type: array
                    items:
                      type: object
                      properties:
                        lesson_id:
                          type: integer
                        title:
                          type: string
                        image:
                          type: string
                          format: url
                        description:
                          type: string
                        progress_status:
                          type: number
                          format: float
                          minimum: 0
                          maximum: 100
              examples:
                example1:
                  value:
                    curriculum:
                      curriculum_id: 1
                      name: "Math Grade 1"
                    lessons:
                      - lesson_id: 101
                        title: "Counting to 10"
                        image: "http://example.com/counting.png"
                        description: "Introduction to numbers."
                        progress_status: 80.0
                      - lesson_id: 102
                        title: "Basic Addition"
                        image: "http://example.com/addition.png"
                        description: "Adding single-digit numbers."
                        progress_status: 45.0
      x-progress-calculation:
        - formula: "progress_status = (completed_activities + completed_quizzes) / (total_activities + total_quizzes) * 100"
        - notes:
            - Only includes activities/quizzes for this lesson
            - "`completed_activities`: Activities with submissions"
            - "`completed_quizzes`: Quizzes with submissions"

  /api/lesson/{lesson_id}:
    get:
      summary: Get Lesson Details
      description: Returns lesson content and completed_at.
      security:
        - ChildToken: [] # Indicates authentication is required with a Child token
      parameters:
        - in: path
          name: lesson_id
          schema:
            type: integer
          required: true
          description: Lesson ID
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  selected_lesson:
                    type: object
                    properties:
                      lesson_id:
                        type: integer
                      title:
                        type: string
                      content:
                        type: string
                        description: HTML formatted content of the lesson.
                      url_details:
                        type: object
                        properties:
                          index:
                            type: string
                            format: url
                      completed_at:
                        type: string
                        format: date-time
                        nullable: true
                        description: ISO format datetime or null if not completed.

  /api/child/{child_id}/lesson/{lesson_id}/mark-read:
    post:
      summary: Mark Lesson as Read
      description: Records lesson completion timestamp.
      parameters:
        - in: path
          name: child_id
          schema:
            type: integer
          required: true
          description: Child ID
        - in: path
          name: lesson_id
          schema:
            type: integer
          required: true
          description: Lesson ID
      requestBody:
        required: false # As completed_at is optional
        content:
          application/json:
            schema:
              type: object
              properties:
                completed_at:
                  type: string
                  format: date-time
                  nullable: true
                  description: ISO format datetime. If not provided, uses current server time.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success]
                  completed_at:
                    type: string
                    format: date-time
              examples:
                success:
                  value:
                    status: "success"
                    completed_at: "2025-06-30T23:31:45.000Z"

components:
  securitySchemes:
    ChildToken:
      type: http
      scheme: bearer
      bearerFormat: JWT # Assuming JWT for token-based authentication
